version: "3"
services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  kvnode:
    image: charmed-bdse-fans/bdse-kvnode
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080
volumes:
  postgres-data:
